name: habit
description: A new Flutter application.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^6.0.5
  bloc: ^6.0.3
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.0
  font_awesome_flutter: ^8.8.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  percent_indicator: ^2.1.7+4
  google_fonts: ^1.1.0
  path: ^1.7.0
  device_preview: ^0.4.8
  shared_preferences: ^0.5.12+2
  flutter_local_notifications: ^3.0.1
  rxdart: ^0.24.1
  device_info: ^0.4.2+9
  workmanager: ^0.2.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.1
  build_runner:



flutter:

  uses-material-design: true
  assets:
   - illustrations/
   - dev_images/
